# **K - MEANS WITH DIFFERENT DISTANCES**

K-MEANS ( WITH MINKOWSKI DISTANCE )

---



In [ ]:
import numpy as np
from scipy.spatial.distance import minkowski
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score
from scipy.stats import mode
import pandas as pd
data = pd.read_csv("/content/heart.csv")
for column in data.select_dtypes(include='object').columns:
    data[column] = LabelEncoder().fit_transform(data[column])
X = data.drop("HeartDisease", axis=1).values
y = data["HeartDisease"].values
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
def kmeans_minkowski(X, n_clusters=3, p=1.5, max_iter=100, tol=1e-4):
    np.random.seed(0)
    initial_centroids_idx = np.random.choice(len(X), n_clusters, replace=False)
    centroids = X[initial_centroids_idx]
    for _ in range(max_iter):
        labels = np.array([np.argmin([minkowski(x, centroid, p=p) for centroid in centroids]) for x in X])
        new_centroids = np.array([X[labels == j].mean(axis=0) for j in range(n_clusters)])
        if np.all(np.abs(new_centroids - centroids) < tol):
            break
        centroids = new_centroids
    return labels, centroids
n_clusters = len(np.unique(y))
labels, centroids = kmeans_minkowski(X_scaled, n_clusters=n_clusters, p=1.5)
label_mapping = np.zeros_like(labels)
for cluster in range(n_clusters):
    mask = (labels == cluster)
    label_mapping[mask] = mode(y[mask])[0]
accuracy = accuracy_score(y, label_mapping)
print("Clustering accuracy:", accuracy)
print("Classification Report:")
print(classification_report(y, label_mapping))
print("Confusion Matrix:")
print(confusion_matrix(y, label_mapping))

Clustering accuracy: 0.8235294117647058
Classification Report:
              precision    recall  f1-score   support

           0       0.76      0.89      0.82       410
           1       0.90      0.77      0.83       508

    accuracy                           0.82       918
   macro avg       0.83      0.83      0.82       918
weighted avg       0.83      0.82      0.82       918

Confusion Matrix:
[[365  45]
 [117 391]]


K - MEANS ( WITH EUCLIDIAN DISTANCE )

---



In [ ]:
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score
from scipy.optimize import linear_sum_assignment
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
data = pd.read_csv('/content/heart.csv')
for column in data.select_dtypes(include='object').columns:
    le = LabelEncoder()
    data[column] = le.fit_transform(data[column])
X = data.drop(columns=['HeartDisease'])
y_true = data['HeartDisease']
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
n_clusters = len(np.unique(y_true))
kmeans = KMeans(n_clusters=n_clusters, random_state=0)
y_pred = kmeans.fit_predict(X_scaled)
def calculate_accuracy(y_true, y_pred):
    contingency_matrix = np.zeros((len(set(y_true)), len(set(y_pred))), dtype=int)
    for i in range(len(y_true)):
        contingency_matrix[y_true.iloc[i], y_pred[i]] += 1
    row_ind, col_ind = linear_sum_assignment(-contingency_matrix)
    accuracy = contingency_matrix[row_ind, col_ind].sum() / len(y_true)
    return accuracy
accuracy = calculate_accuracy(y_true, y_pred)
print("Clustering Accuracy:", accuracy)
print("Classification Report:")
print(classification_report(y, label_mapping))
print("Confusion Matrix:")
print(confusion_matrix(y, label_mapping))

Clustering Accuracy: 0.8289760348583878
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       410
           1       0.55      1.00      0.71       508

    accuracy                           0.55       918
   macro avg       0.28      0.50      0.36       918
weighted avg       0.31      0.55      0.39       918

Confusion Matrix:
[[  0 410]
 [  0 508]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


K - MEANS ( WITH MAHALANOBIS DISTANCE )

---



In [ ]:
import numpy as np
from scipy.spatial.distance import mahalanobis
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score
from scipy.stats import mode
import pandas as pd
data = pd.read_csv("/content/heart.csv")
for column in data.select_dtypes(include='object').columns:
    data[column] = LabelEncoder().fit_transform(data[column])
X = data.drop("HeartDisease", axis=1).values
y = data["HeartDisease"].values
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
cov_matrix = np.cov(X_scaled, rowvar=False)
inv_cov_matrix = np.linalg.inv(cov_matrix)
def kmeans_mahalanobis(X, inv_cov_matrix, n_clusters=3, max_iter=100, tol=1e-4):
    np.random.seed(0)
    initial_centroids_idx = np.random.choice(len(X), n_clusters, replace=False)
    centroids = X[initial_centroids_idx]
    for _ in range(max_iter):
        labels = np.array([np.argmin([mahalanobis(x, centroid, inv_cov_matrix) for centroid in centroids]) for x in X])
        new_centroids = np.array([X[labels == j].mean(axis=0) for j in range(n_clusters)])
        if np.all(np.abs(new_centroids - centroids) < tol):
            break
        centroids = new_centroids
    return labels, centroids
n_clusters = len(np.unique(y))
labels, centroids = kmeans_mahalanobis(X_scaled, inv_cov_matrix, n_clusters=n_clusters)
label_mapping = np.zeros_like(labels)
for cluster in range(n_clusters):
    mask = (labels == cluster)
    label_mapping[mask] = mode(y[mask])[0]
accuracy = accuracy_score(y, label_mapping)
print("Clustering accuracy:", accuracy)
print("Classification Report:")
print(classification_report(y, label_mapping))
print("Confusion Matrix:")
print(confusion_matrix(y, label_mapping))

Clustering accuracy: 0.5533769063180828
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       410
           1       0.55      1.00      0.71       508

    accuracy                           0.55       918
   macro avg       0.28      0.50      0.36       918
weighted avg       0.31      0.55      0.39       918

Confusion Matrix:
[[  0 410]
 [  0 508]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


K - MEANS ( WITH JACCARD SCORE )

---



In [ ]:
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, jaccard_score, classification_report, confusion_matrix
from scipy.stats import mode
import pandas as pd
data = pd.read_csv("/content/heart.csv")
for column in data.select_dtypes(include='object').columns:
    data[column] = LabelEncoder().fit_transform(data[column])
X = data.drop("HeartDisease", axis=1).values
y = data["HeartDisease"].values
def jaccard_distance(a, b):
    intersection = np.sum(np.minimum(a, b))
    union = np.sum(np.maximum(a, b))
    return 1 - intersection / union
def kmeans_jaccard(X, n_clusters=3, max_iter=100, tol=1e-4):
    np.random.seed(0)
    initial_centroids_idx = np.random.choice(len(X), n_clusters, replace=False)
    centroids = X[initial_centroids_idx]
    for _ in range(max_iter):
        labels = np.array([np.argmin([jaccard_distance(x, centroid) for centroid in centroids]) for x in X])
        new_centroids = np.array([X[labels == j].mean(axis=0) for j in range(n_clusters)])
        if np.all(np.abs(new_centroids - centroids) < tol):
            break
        centroids = new_centroids
    return labels, centroids
n_clusters = len(np.unique(y))
labels, centroids = kmeans_jaccard(X, n_clusters=n_clusters)
label_mapping = np.zeros_like(labels)
for cluster in range(n_clusters):
    mask = (labels == cluster)
    label_mapping[mask] = mode(y[mask])[0]
accuracy = accuracy_score(y, label_mapping)
print("Clustering accuracy:", accuracy)
print("Classification Report:")
print(classification_report(y, label_mapping))
print("Confusion Matrix:")
print(confusion_matrix(y, label_mapping))

Clustering accuracy: 0.5904139433551199
Classification Report:
              precision    recall  f1-score   support

           0       0.52      0.95      0.67       410
           1       0.88      0.30      0.45       508

    accuracy                           0.59       918
   macro avg       0.70      0.62      0.56       918
weighted avg       0.72      0.59      0.55       918

Confusion Matrix:
[[389  21]
 [355 153]]


#**RANDOM FOREST CLASSIFIER**


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
data = pd.read_csv("/content/heart.csv")
label_encoder = LabelEncoder()
for column in data.select_dtypes(include=['object']).columns:
    data[column] = label_encoder.fit_transform(data[column])
X = data.drop(columns=["HeartDisease"])
y = data["HeartDisease"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 89.49%
Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.89      0.87       112
           1       0.92      0.90      0.91       164

    accuracy                           0.89       276
   macro avg       0.89      0.89      0.89       276
weighted avg       0.90      0.89      0.90       276

Confusion Matrix:
[[100  12]
 [ 17 147]]


#**X - BOOST**



In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
data = pd.read_csv("/content/heart.csv")
label_encoder = LabelEncoder()
for column in data.select_dtypes(include=['object']).columns:
    data[column] = label_encoder.fit_transform(data[column])
X = data.drop(columns=["HeartDisease"])
y = data["HeartDisease"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
xgb_model = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
xgb_model.fit(X_train, y_train)
y_pred = xgb_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

/usr/local/lib/python3.10/dist-packages/xgboost/core.py:158: UserWarning: [15:02:44] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Accuracy: 85.87%
Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.87      0.83       112
           1       0.90      0.85      0.88       164

    accuracy                           0.86       276
   macro avg       0.85      0.86      0.86       276
weighted avg       0.86      0.86      0.86       276

Confusion Matrix:
[[ 97  15]
 [ 24 140]]
